spring:
  application:
    name: embabel-shell-demo

openrouter:
  base-url: https://openrouter.ai
  api-key: ${OPENROUTER_API_KEY}
  completions-path: /api/v1/chat/completions
  chat:
    model: deepseek/deepseek-chat-v3.1:free

embabel:
  models:
    default-llm: qwen3:8b
    #default-llm: deepseek/deepseek-chat-v3.1:free
    llms:
      better: gpt-5-mini
      cheaper: gpt-oss:20b
      faster: llama3.2:latest