spring:
  application:
    name: embabel-webapp-demo

embabel:
  models:
    default-llm: qwen3:8b
    llms:
      better: gpt-5-mini
      cheaper: gpt-oss:20b
      faster: llama3.2:latest

logging:
  level:
    com:
      embabel: DEBUG